- name: Post configure rocky systems
  hosts: rocky
  become: yes

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Set static IP using nmcli
      become: yes
      ansible.builtin.shell: |
        nmcli con mod "{{ nmcli_con_name }}" ipv4.method manual
        nmcli con mod "{{ nmcli_con_name }}" ipv4.addresses {{ new_ip }}/24
        nmcli con mod "{{ nmcli_con_name }}" ipv4.gateway 10.0.5.2
        nmcli con mod "{{ nmcli_con_name }}" ipv4.dns 10.0.17.4
        nmcli con up "{{ nmcli_con_name }}"
      when: ansible_distribution == "Rocky"


    - name: Add deployer to sudoers.d
      copy:
        content: "deployer ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/deployer
        mode: '0440'

    - name: Reboot to apply changes
      reboot:
        reboot_timeout: 10000
